import { ChainID } from "./chain-id"

const data: { [key: string]: string } = {
  [ChainID.ETHEREUM_MAINNET]: "https://etherscan.io",
  [ChainID.ETHEREUM_GOERLI]: "https://goerli.etherscan.io",
  [ChainID.ETHEREUM_SEPOLIA]: "https://sepolia.etherscan.io",
  [ChainID.ETHEREUM_HOLESKY]: "https://holesky.etherscan.io",
  [ChainID.METIS_ANDROMEDA]: "https://andromeda-explorer.metis.io",
  [ChainID.METIS_SEPOLIA]: "https://sepolia.explorer.metisdevops.link",
  [ChainID.ARBITRUM_ONE]: "https://arbiscan.io",
  [ChainID.ARBITRUM_GOERLI]: "https://goerli.arbiscan.io",
  [ChainID.ARBITRUM_NOVA]: "https://nova.arbiscan.io",
  [ChainID.OASIS_EMERALD]: "https://explorer.emerald.oasis.dev",
  [ChainID.OASIS_SAPPHIRE]: "https://explorer.sapphire.oasis.io",
  [ChainID.OASIS_SAPPHIRE_TESTNET]:
    "https://testnet.explorer.sapphire.oasis.dev",
  [ChainID.IMMUTABLE_MAINNET]: "https://explorer.immutable.com",
  [ChainID.IMMUTABLE_TESTNET]: "https://explorer.testnet.immutable.com",
  [ChainID.AVALANCHE_MAINNET]: "https://snowtrace.io",
  [ChainID.AVALANCHE_FUJI]: "https://testnet.snowtrace.io",
  [ChainID.POLYGON_MAINNET]: "https://polygonscan.com",
  [ChainID.POLYGON_MUMBAI]: "https://mumbai.polygonscan.com",
  [ChainID.OPTIMISM_MAINNET]: "https://optimistic.etherscan.io",
  [ChainID.OPTIMISM_SEPOLIA]: "https://sepolia-optimism.etherscan.io",
  [ChainID.FANTOM_MAINNET]: "https://ftmscan.com",
  [ChainID.FANTOM_TESTNET]: "https://testnet.ftmscan.com",
  [ChainID.BASE_MAINNET]: "https://basescan.org",
  [ChainID.BASE_SEPOLIA]: "https://sepolia.basescan.org",
  [ChainID.BNB_MAINNET]: "https://bscscan.com",
  [ChainID.BNB_TESTNET]: "https://testnet.bscscan.com",
  [ChainID.LINEA_MAINNET]: "https://lineascan.build",
  [ChainID.LINEA_TESTNET]: "https://goerli.lineascan.build",
  [ChainID.MOONBEAM_MAINNET]: "https://moonbeam.moonscan.io",
  [ChainID.MOONBASE_ALPHA]: "https://moonbase.moonscan.io",
  [ChainID.MOONRIVER_MAINNET]: "https://moonriver.moonscan.io",
  [ChainID.CELO_MAINNET]: "https://celoscan.io",
  [ChainID.CELO_ALFAJORES]: "https://alfajores.celoscan.io",
  [ChainID.GNOSIS_MAINNET]: "https://gnosisscan.io",
  [ChainID.CRONOS_MAINNET]: "https://cronoscan.com",
  [ChainID.SCROLL_MAINNET]: "https://scrollscan.com",
  [ChainID.SCROLL_SEPOLIA]: "https://sepolia.scrollscan.com",
  [ChainID.MANTLE_MAINNET]: "https://explorer.mantle.xyz",
  [ChainID.MANTLE_TESTNET]: "https://explorer.testnet.mantle.xyz",
  [ChainID.BITTORRENT_MAINNET]: "https://bttcscan.com",
  [ChainID.BITTORRENT_TESTNET]: "https://testnet.bttcscan.com",
  [ChainID.XDC_MAINNET]: "https://explorer.xinfin.network",
  [ChainID.CANTO_MAINNET]: "https://tuber.build",
  [ChainID.CANTO_TESTNET]: "https://testnet.tuber.build",
  [ChainID.KAVA_MAINNET]: "https://kavascan.com",
  [ChainID.KAVA_TESTNET]: "https://testnet.kavascan.com",
  [ChainID.ROLLUX_MAINNET]: "https://explorer.rollux.com",
  [ChainID.ROLLUX_TESTNET]: "https://rollux.tanenbaum.io",
  [ChainID.SYSCOIN_MAINNET]: "https://explorer.syscoin.org",
  [ChainID.SYSCOIN_TESTNET]: "https://tanenbaum.io",
  [ChainID.BOBA_ETHEREUM]: "https://bobascan.com",
  [ChainID.MANTA_PACIFIC]: "https://pacific-explorer.manta.network",
  [ChainID.MANTA_TESTNET]: "https://pacific-explorer.testnet.manta.network",
  [ChainID.WEMIX_MAINNET]: "https://wemixscan.com",
  [ChainID.WEMIX_TESTNET]: "https://testnet.wemixscan.com",
  [ChainID.ASTAR_MAINNET]: "https://astar.blockscout.com",
  [ChainID.SHIDEN_MAINNET]: "https://shiden.blockscout.com",
  [ChainID.SHUBIYA_TESTNET]: "https://shibuya.blockscout.com",
  [ChainID.ZETACHAIN_MAINNET]: "",
  [ChainID.ZETACHAIN_TESTNET]: "https://zetachain-athens-3.blockscout.com",
  [ChainID.FLARE_MAINNET]: "https://flare-explorer.flare.network",
  [ChainID.FLARE_COSTON]: "https://coston-explorer.flare.network",
  [ChainID.FLARE_COSTON2]: "https://coston2-explorer.flare.network",
  [ChainID.FUSE_MAINNET]: "https://explorer.fuse.io",
  [ChainID.FUSE_SPARK]: "https://explorer.fusespark.io",
  [ChainID.SHIBARIUM_MAINNET]: "https://www.shibariumscan.io",
  [ChainID.PUPPYNET_TESTNET]: "https://puppyscan.shib.io",
  [ChainID.CONFLUX_MAINNET]: "https://evm.confluxscan.io",
  [ChainID.CONFLUX_TESTNET]: "https://evmtestnet.confluxscan.net",
  [ChainID.FILECOIN_MAINNET]: "https://fvm.starboard.ventures/explorer",
  [ChainID.FILECOIN_CALIBRATION]:
    "https://fvm.starboard.ventures/calibration/explorer",
  [ChainID.ENERGY_WEB_CHAIN]: "https://explorer.energyweb.org",
  [ChainID.ENERGY_WEB_CHAIN_TESTNET]: "https://explorer.testnet.energyweb.org",
  [ChainID.LUKSO_MAINNET]: "https://explorer.execution.mainnet.lukso.network",
  [ChainID.LUKSO_TESTNET]: "https://explorer.execution.testnet.lukso.network",
  [ChainID.ACALA_MAINNET]: "https://blockscout.acala.network",
  [ChainID.MANDALA_TESTNET]: "https://blockscout.mandala.aca-staging.network",
  [ChainID.REI_MAINNET]: "https://scan.rei.network",
  [ChainID.REI_TESTNET]: "https://scan-test.rei.network",
  [ChainID.ZORA_NETWORK_MAINNET]: "https://explorer.zora.energy",
  [ChainID.CALLISTO_MAINNET]: "https://explorer.callisto.network",
  [ChainID.ZKSYNC_MAINNET]: "https://explorer.zksync.io",
  [ChainID.ZKSYNC_SEPOLIA]: "https://sepolia.explorer.zksync.io",
  [ChainID.NEON_MAINNET]: "https://neon.blockscout.com",
  [ChainID.NEON_TESTNET]: "https://neon-devnet.blockscout.com",
  [ChainID.AURORA_MAINNET]: "https://explorer.mainnet.aurora.dev",
  [ChainID.AURORA_TESTNET]: "https://explorer.testnet.aurora.dev",
  [ChainID.RONIN_MAINNET]: "https://app.roninchain.com",
  [ChainID.RONIN_SAIGON_TESTNET]: "https://saigon-app.roninchain.com",
  [ChainID.TRON_MAINNET]: "https://tronscan.org/#",
  [ChainID.TRON_SHASTA_TESTNET]: "https://shasta.tronscan.org/#",
  [ChainID.BEAM_MAINNET]: "https://avascan.info/blockchain/beam",
  [ChainID.CARBON_EVM_MAINNET]: "https://evm-scan.carbon.network",
  [ChainID.CARBON_EVM_TESTNET]: "https://test-evm-scan.carbon.network",
}

export const getExplorer = (network: string): string => data[network] || ""
