import { ChainID } from "./chain-id";

export const getAPI = (network: string): string => {
    switch (network) {
        case ChainID.ETHEREUM_MAINNET:
            return "https://api.etherscan.io";
        case ChainID.ETHEREUM_GOERLI:
            return "https://api-goerli.etherscan.io";
        case ChainID.ETHEREUM_SEPOLIA:
            return "https://api-sepolia.etherscan.io";
        case ChainID.ETHEREUM_HOLESKY:
            return "https://api-holesky.etherscan.io";
        case ChainID.METIS_ANDROMEDA:
            return "https://andromeda-explorer.metis.io";
        case ChainID.METIS_SEPOLIA:
            return "https://sepolia.explorer.metisdevops.link";
        case ChainID.ARBITRUM_ONE:
            return "https://api.arbiscan.io";
        case ChainID.ARBITRUM_GOERLI:
            return "https://api-goerli.arbiscan.io";
        case ChainID.ARBITRUM_NOVA:
            return "https://api-nova.arbiscan.io";
        case ChainID.OASIS_EMERALD:
            return "https://explorer.emerald.oasis.dev";
        case ChainID.OASIS_SAPPHIRE:
            return "https://explorer.sapphire.oasis.io";
        case ChainID.OASIS_SAPPHIRE_TESTNET:
            return "https://testnet.explorer.sapphire.oasis.dev";
        case ChainID.IMMUTABLE_MAINNET:
            return "https://explorer.immutable.com";
        case ChainID.IMMUTABLE_MAINNET:
            return "https://explorer.immutable.com";
        case ChainID.IMMUTABLE_TESTNET:
            return "https://explorer.testnet.immutable.com";

        case ChainID.AVALANCHE_MAINNET:
            return "https://api.routescan.io/v2/network/mainnet/evm/43114/etherscan";
        case ChainID.AVALANCHE_FUJI:
            return "https://api.routescan.io/v2/network/testnet/evm/43113/etherscan";
        case ChainID.POLYGON_MAINNET:
            return "https://api.polygonscan.com";
        case ChainID.POLYGON_MUMBAI:
            return "https://api-mumbai.polygonscan.com";
        case ChainID.OPTIMISM_MAINNET:
            return "https://api-optimistic.etherscan.io";
        case ChainID.OPTIMISM_SEPOLIA:
            return "https://api-goerli-optimistic.etherscan.io";
        case ChainID.FANTOM_MAINNET:
            return "https://api.ftmscan.com";
        case ChainID.FANTOM_TESTNET:
            return "https://api-testnet.ftmscan.com";
        case ChainID.BASE_MAINNET:
            return "https://api.basescan.org";
        case ChainID.BASE_SEPOLIA:
            return "https://api-sepolia.basescan.org";
        case ChainID.BNB_MAINNET:
            return "https://api.bscscan.com";
        case ChainID.BNB_TESTNET:
            return "https://api-testnet.bscscan.com"
        case ChainID.LINEA_MAINNET:
            return "https://api.lineascan.build";
        case ChainID.LINEA_TESTNET:
            return "https://api-testnet.lineascan.build";
        case ChainID.MOONBEAM_MAINNET:
            return "https://api-moonbeam.moonscan.io";
        case ChainID.MOONBASE_ALPHA:
            return "https://api-moonbase.moonscan.io";
        case ChainID.MOONRIVER_MAINNET:
            return "https://api-moonriver.moonscan.io";
        case ChainID.CELO_MAINNET:
            return "https://api.celoscan.io";
        case ChainID.CELO_ALFAJORES:
            return "https://api-alfajores.celoscan.io";
        case ChainID.GNOSIS_MAINNET:
            return "https://api.gnosisscan.io";
        case ChainID.CRONOS_MAINNET:
            return "https://api.cronoscan.com";
        case ChainID.SCROLL_MAINNET:
            return "https://api.scrollscan.com";
        case ChainID.SCROLL_SEPOLIA:
            return "https://api-sepolia.scrollscan.com";
        case ChainID.MANTLE_MAINNET:
            return "https://explorer.mantle.xyz";
        case ChainID.MANTLE_TESTNET:
            return "https://explorer.testnet.mantle.xyz";
        case ChainID.BITTORRENT_MAINNET:
            return "https://api.bttcscan.com";
        case ChainID.BITTORRENT_TESTNET:
            return "https://api-testnet.bttcscan.com";
        case ChainID.XDC_MAINNET:
            return "https://xdc.blocksscan.io";
        case ChainID.CANTO_MAINNET:
            return "https://explorer.plexnode.wtf";
        case ChainID.CANTO_TESTNET:
            return "https://testnet.tuber.build"
        case ChainID.KAVA_MAINNET:
            return "https://kavascan.com"
        case ChainID.KAVA_TESTNET:
            return "https://testnet.kavascan.com"
        case ChainID.ROLLUX_MAINNET:
            return "https://explorer.rollux.com"
        case ChainID.ROLLUX_TESTNET:
            return "https://rollux.tanenbaum.io"
        case ChainID.SYSCOIN_MAINNET:
            return "https://explorer.syscoin.org"
        case ChainID.SYSCOIN_TESTNET:
            return "https://tanenbaum.io"
        case ChainID.BOBA_ETHEREUM:
            return "https://api.routescan.io/v2/network/mainnet/evm/288/etherscan";
        case ChainID.MANTA_PACIFIC:
            return "https://pacific-explorer.manta.network";
        case ChainID.MANTA_TESTNET:
            return "https://pacific-explorer.testnet.manta.network";
        case ChainID.WEMIX_MAINNET:
            return "https://api.wemixscan.com";
        case ChainID.WEMIX_TESTNET:
            return "https://api-testnet.wemixscan.com";
        case ChainID.ASTAR_MAINNET:
            return "https://blockscout.com/astar"; // No API Support yet... "https://astar.blockscout.com";
        case ChainID.SHIDEN_MAINNET:
            return "https://blockscout.com/shiden"; // No API Support yet... "https://shiden.blockscout.com";
        case ChainID.SHUBIYA_TESTNET:
            return "https://blockscout.com/shibuya"; // No API Support yet... "https://shibuya.blockscout.com";
        case ChainID.ZETACHAIN_MAINNET:
            return "";
        case ChainID.ZETACHAIN_TESTNET:
            return "https://zetachain-athens-3.blockscout.com";
        case ChainID.FLARE_MAINNET:
            return "https://flare-explorer.flare.network";
        case ChainID.FLARE_COSTON:
            return "https://coston-explorer.flare.network";
        case ChainID.FLARE_COSTON2:
            return "https://coston2-explorer.flare.network";
        case ChainID.FUSE_MAINNET:
            return "https://explorer.fuse.io";
        case ChainID.FUSE_SPARK:
            return "https://explorer.fusespark.io"
        case ChainID.SHIBARIUM_MAINNET:
            return "https://www.shibariumscan.io";
        case ChainID.PUPPYNET_TESTNET:
            return "https://puppyscan.shib.io";
        case ChainID.CONFLUX_MAINNET:
            return "https://evmapi.confluxscan.io";
        case ChainID.CONFLUX_TESTNET:
            return "https://evmapi-testnet.confluxscan.net";
        case ChainID.FILECOIN_MAINNET:
            return "https://fvm-api.starboard.ventures";
        case ChainID.FILECOIN_CALIBRATION:
            return "https://fvm-calibration-api.starboard.ventures";
        case ChainID.ENERGY_WEB_CHAIN:
            return "https://explorer.energyweb.org";
        case ChainID.ENERGY_WEB_CHAIN_TESTNET:
            return "https://explorer.testnet.energyweb.org";
        case ChainID.LUKSO_MAINNET:
            return "https://api.explorer.execution.mainnet.lukso.network";
        case ChainID.LUKSO_TESTNET:
            return "https://api.explorer.execution.testnet.lukso.network";
        case ChainID.ACALA_MAINNET:
            return "https://blockscout.acala.network";
        case ChainID.MANDALA_TESTNET:
            return "https://blockscout.mandala.aca-staging.network";
        case ChainID.REI_MAINNET:
            return "https://scan.rei.network";
        case ChainID.REI_TESTNET:
            return "https://scan-test.rei.network";
        case ChainID.ZORA_NETWORK_MAINNET:
            return "https://explorer.zora.energy";
        case ChainID.CALLISTO_MAINNET:
            return "https://explorer.callisto.network";
        case ChainID.ZKSYNC_MAINNET:
            return "https://block-explorer-api.mainnet.zksync.io";
        case ChainID.ZKSYNC_SEPOLIA:
            return "https://block-explorer-api.mainnet.zksync.io";
        case ChainID.NEON_MAINNET:
            return "https://neon.blockscout.com";
        case ChainID.NEON_TESTNET:
            return "https://neon-devnet.blockscout.com";
        case ChainID.AURORA_MAINNET:
            return "https://old.explorer.aurora.dev";
        case ChainID.AURORA_TESTNET:
            return "https://explorer.old.testnet.aurora.dev";
        case ChainID.RONIN_MAINNET:
        case ChainID.RONIN_SAIGON_TESTNET:
            return "https://explorer-kintsugi.roninchain.com";
        case ChainID.TRON_MAINNET:
            return "https://apilist.tronscanapi.com/api/solidity/contract/info"
        case ChainID.TRON_SHASTA_TESTNET:
            return "https://shastapi.tronscan.org/api/solidity/contract/info";
        case ChainID.BEAM_MAINNET:
            return "https://api.routescan.io/v2/network/mainnet/evm/4337/etherscan";
        case ChainID.CARBON_EVM_MAINNET:
            return "https://evm-scan.carbon.network"
        case ChainID.CARBON_EVM_TESTNET:
            return "https://test-evm-scan.carbon.network"
        default:
            return "";
    }
}
