import { ChainID } from "./chain-id"

export const data: { [key: string]: string } = {
  [ChainID.ETHEREUM_MAINNET]: "Etheruem Mainnet",
  [ChainID.ETHEREUM_GOERLI]: "Etheruem Goerli",
  [ChainID.ETHEREUM_SEPOLIA]: "Etheruem Seoplia",
  [ChainID.ETHEREUM_HOLESKY]: "Holesky Test Network",
  [ChainID.METIS_ANDROMEDA]: "Metis Andormeda",
  [ChainID.METIS_SEPOLIA]: "Metis Seoplia",
  [ChainID.ARBITRUM_ONE]: "Arbitrum One",
  [ChainID.ARBITRUM_GOERLI]: "Arbitrum Goerli",
  [ChainID.ARBITRUM_NOVA]: "Arbitrum Nova",
  [ChainID.OASIS_EMERALD]: "Oasis Emerald",
  [ChainID.OASIS_SAPPHIRE]: "Oasis Sapphire",
  [ChainID.OASIS_SAPPHIRE_TESTNET]: "Oasis Sapphire Testnet",
  [ChainID.IMMUTABLE_MAINNET]: "Immutable Mainnet",
  [ChainID.IMMUTABLE_TESTNET]: "Immutable Testnet",
  [ChainID.AVALANCHE_MAINNET]: "Avalanche Mainnet",
  [ChainID.AVALANCHE_FUJI]: "Avalanche Testnet",
  [ChainID.POLYGON_MAINNET]: "Polygon Mainnet",
  [ChainID.POLYGON_MUMBAI]: "Polygon Mumbai",
  [ChainID.OPTIMISM_MAINNET]: "Optimism Mainnet",
  [ChainID.OPTIMISM_SEPOLIA]: "Optimism Seoplia",
  [ChainID.FANTOM_MAINNET]: "Fantom Mainnet",
  [ChainID.FANTOM_TESTNET]: "Fantom Testnet",
  [ChainID.BASE_MAINNET]: "Base Mainnet",
  [ChainID.BASE_SEPOLIA]: "Base Seoplia",
  [ChainID.BNB_MAINNET]: "BNB Smart Chain",
  [ChainID.BNB_TESTNET]: "BNB Smart Chain Testnet",
  [ChainID.LINEA_MAINNET]: "Linea Mainnet",
  [ChainID.LINEA_TESTNET]: "Linea Testnet",
  [ChainID.MOONBEAM_MAINNET]: "Moonbeam Mainnet",
  [ChainID.MOONBASE_ALPHA]: "Moonbase Alpha Testnet",
  [ChainID.MOONRIVER_MAINNET]: "Moonriver",
  [ChainID.CELO_MAINNET]: "Celo Mainnet",
  [ChainID.CELO_ALFAJORES]: "Celo Alfajores Testnet",
  [ChainID.GNOSIS_MAINNET]: "Gnosis Mainnet",
  [ChainID.CRONOS_MAINNET]: "Cronos Mainnet",
  [ChainID.SCROLL_MAINNET]: "Scroll Mainnet",
  [ChainID.SCROLL_SEPOLIA]: "Scroll Seoplia",
  [ChainID.MANTLE_MAINNET]: "Mantle",
  [ChainID.MANTLE_TESTNET]: "Mantle Testnet",
  [ChainID.BITTORRENT_MAINNET]: "BitTorrent Mainnet",
  [ChainID.BITTORRENT_TESTNET]: "Donau Testnet",
  [ChainID.XDC_MAINNET]: "XDC Network",
  [ChainID.CANTO_MAINNET]: "Canto Mainnet",
  [ChainID.CANTO_TESTNET]: "Canto Testnet",
  [ChainID.KAVA_MAINNET]: "Kava Mainnet",
  [ChainID.KAVA_TESTNET]: "Kava Testnet",
  [ChainID.ROLLUX_MAINNET]: "Rollux",
  [ChainID.ROLLUX_TESTNET]: "Rollux Tanenbaum Testnet",
  [ChainID.SYSCOIN_MAINNET]: "Syscoin Mainnet",
  [ChainID.SYSCOIN_TESTNET]: "Syscoin Tanenbaum Testnet",
  [ChainID.BOBA_ETHEREUM]: "Boba Mainnet",
  [ChainID.MANTA_PACIFIC]: "Manta Pacific Mainnet",
  [ChainID.MANTA_TESTNET]: "Manta Pacific Testnet",
  [ChainID.WEMIX_MAINNET]: "Wemix3.0 Mainnet",
  [ChainID.WEMIX_TESTNET]: "Wemix3.0 Testnet",
  [ChainID.ASTAR_MAINNET]: "Astar",
  [ChainID.SHIDEN_MAINNET]: "Shiden",
  [ChainID.SHUBIYA_TESTNET]: "Shubiya",
  [ChainID.ZETACHAIN_MAINNET]: "ZetaChain Mainnet",
  [ChainID.ZETACHAIN_TESTNET]: "ZetaChain Athena 3 Testnet",
  [ChainID.FLARE_MAINNET]: "Flare Mainnet",
  [ChainID.FLARE_COSTON]: "Flare Coston Testnet",
  [ChainID.FLARE_COSTON2]: "Flare Coston 2 Testnet",
  [ChainID.FUSE_MAINNET]: "Fuse Mainnet",
  [ChainID.FUSE_SPARK]: "Fuse Spark Tesnet",
  [ChainID.SHIBARIUM_MAINNET]: "Shibarium Mainnet",
  [ChainID.PUPPYNET_TESTNET]: "Puppynet Testnet",
  [ChainID.CONFLUX_MAINNET]: "Conflux eSpace Mainnet",
  [ChainID.CONFLUX_TESTNET]: "Conflux eSpace Testnet",
  [ChainID.FILECOIN_MAINNET]: "Filecoin Mainnet",
  [ChainID.FILECOIN_CALIBRATION]: "Filecoin Calibration Testnet",
  [ChainID.ENERGY_WEB_CHAIN]: "Energy Web Mainnet",
  [ChainID.ENERGY_WEB_CHAIN_TESTNET]: "Energy Web Volta Testnet",
  [ChainID.LUKSO_MAINNET]: "Lukso Mainnet",
  [ChainID.LUKSO_TESTNET]: "Lukso Testnet",
  [ChainID.ACALA_MAINNET]: "Acala Mainnet",
  [ChainID.MANDALA_TESTNET]: "Mandala Testnet",
  [ChainID.REI_MAINNET]: "Rei Network",
  [ChainID.REI_TESTNET]: "Rei Testnet",
  [ChainID.ZORA_NETWORK_MAINNET]: "Zora Network",
  [ChainID.ZORA_NETWORK_TESTNET]: "Zora Testnet",
  [ChainID.CALLISTO_MAINNET]: "Callisto Network",
  [ChainID.ZKSYNC_MAINNET]: "zkSync Mainnet",
  [ChainID.ZKSYNC_SEPOLIA]: "zkSync Seoplia",
  [ChainID.NEON_MAINNET]: "Neon Mainnet",
  [ChainID.NEON_TESTNET]: "Neon Devnet",
  [ChainID.AURORA_MAINNET]: "Aurora Mainnet",
  [ChainID.AURORA_TESTNET]: "Aurora Testnet",
  [ChainID.RONIN_MAINNET]: "Ronin Network",
  [ChainID.RONIN_SAIGON_TESTNET]: "Ronin Saigon Testnet",
  [ChainID.TRON_MAINNET]: "Tron Mainnet",
  [ChainID.TRON_NILE_TESTNET]: "Tron Nile Testnet",
  [ChainID.TRON_SHASTA_TESTNET]: "Tron Shasta Testnet",
  [ChainID.BEAM_MAINNET]: "Beam",
  [ChainID.CARBON_EVM_MAINNET]: "Carbon EVM",
  [ChainID.CARBON_EVM_TESTNET]: "Carbon EVM Testnet",
  [ChainID.ARTELA]: "Artela",
  [ChainID.ARTELA_TESTNET]: "Artela Testnet",
  [ChainID.BERACHAIN_TESTNET]: "Berachain Artio",
  [ChainID.VICTION_MAINNET]: "Viction",
  [ChainID.VICTION_TESTNET]: "Viction Testnet",
  [ChainID.PALM_MAINNET]: "Palm",
  [ChainID.PALM_TESTNET]: "Palm Testnet",
  [ChainID.METER_MAINNET]: "Meter Mainnet",
  [ChainID.METER_TESTNET]: "Meter Testnet",
  [ChainID.PUBLIC_GOOD_NETWORK]: "PGN (Public Goods Network)",
  [ChainID.PUBLIC_GOOD_NETWORK_SEPOLIA]: "PGN Testnet (Public Goods Network)",
  [ChainID.ROOTSTOCK_MAINNET]: "Rootstock Mainnet",
  [ChainID.ROOTSTOCK_TESTNET]: "Rootstock Testnet",
  [ChainID.LIGHTLINK_PHOENIX_MAINNET]: "Lightlink Phoenix Mainnet",
  [ChainID.LIGHTLINK_PEGASUS_TESTNET]: "Lightlink Pegasus Testnet",
  [ChainID.ETHERLINK_MAINNET]: "Etherlink Mainnet",
  [ChainID.ETHERLINK_TESTNET]: "Etherlink Testnet",
  [ChainID.SHARDEUM_SPHINX_1_X]: "Shardeum Sphinx 1.x",
  [ChainID.VELAS_MAINNET]: "Velas Mainnet",
  [ChainID.MODE_MAINNET]: "Mode Mainnet",
  [ChainID.MODE_SEPOLIA]: "Mode Seoplia",
  [ChainID.MORPH]: "Morph L2",
  [ChainID.MORPH_TESTNET]: "Morph Testnet",
  [ChainID.BLAST_MAINNET]: "Blast Mainnet",
  [ChainID.BLAST_SEPOLIA]: "Blast Seoplia",
  [ChainID.SYNDICATE_FRAME_MAINNET]: "Syndicate Frame Chain",
  [ChainID.DOS_MAINNET]: "DOS Chain",
  [ChainID.DOS_TESTNET]: "DOS Testnet",
  [ChainID.DEGEN_MAINNET]: "Degen Chain",
  [ChainID.TAIKO_MAINNET]: "Taiko Mainnet",
  [ChainID.TAIKO_HEKLA_TESTNET]: "Taiko Testnet",
  [ChainID.TAIKO_KATLA_TESTNET]: "Taike Katla Testnet",
  [ChainID.SHIMMER_MAINNET]: "Shimmer Mainnet",
  [ChainID.SHIMMER_TESTNET]: "Shimmer Testnet",
  [ChainID.FRAXSCAN_MAINNET]: "Fraxscan Mainnet",
  [ChainID.FRAXSCAN_TESTNET]: "Fraxscan Holesky",
  [ChainID.XRP_SIDECHAIN]: "XRP Sidechain",
  [ChainID.CORE_MAINNET]: "Core",
  [ChainID.ZKEVM_POLYGON]: "Polygon zkEVM",
  [ChainID.ZKEVM_POLYGON_CARDONA]: "Polygon zkEVM Cardona",
  [ChainID.BITLAYER_MAINNET]: "Bitlayer Mainnet",
  [ChainID.BITLAYER_TESTNET]: "Bitlayer Testnet",
  [ChainID.ETHEREUM_CLASSIC_MAINNET]: "Etheruem Classic",
  [ChainID.ETHEREUM_CLASSIC_TESTNET]: "Etheruem Classic Testnet",
  [ChainID.STABILITY_MAINNET]: "Global Trust Network",
  [ChainID.STABILITY_TESTNET]: "Stability Testnet",
  [ChainID.ARBITRUM_SEPOLIA]: "Arbitrum Seoplia",
  [ChainID.KROMA_MAINNET]: "Kroma Mainnet",
  [ChainID.KROMA_SEPOLIA]: "Kroma Seoplia",
  [ChainID.POLYGON_AMOY]: "Polygon Amoy",
  [ChainID.GNOSIS_CHIADO]: "Gnosis Chiado",
  [ChainID.COTI_DEVNET]: "Coti Devnet",
  [ChainID.COTI_TESTNET]: "Coti Testnet",
  [ChainID.COTI_MAINNET]: "Coti Mainnet",
  [ChainID.LISK_MAINNET]: "Lisk Mainnet",
  [ChainID.LISK_SEPOLIA]: "Lisk Seoplia",
  [ChainID.REDSTONE_MAINNET]: "Redstone Mainnet",
  [ChainID.REDSTONE_GARNET_TESTNET]: "Redstone Garnet Testnet",
  [ChainID.OPEN_CAMPUS_CODEX]: "Open Campus Codex",
  [ChainID.UNICHAIN_SEPOLIA]: "Unichain Sepolia",
  [ChainID.MOVEMENT_IMOLA]: "Movement Imola",
  [ChainID.XAI_GAMES_MAINNET]: "Xai Games Mainnet",
  [ChainID.XAI_ARB_TESTNET]: "Xai Arb Sepolia",
  [ChainID.SONEIUM_TESTNET]: "Soneium Minato Testnet",
  [ChainID.BLACKFORT_MAINNET]: "BXN Mainnet",
  [ChainID.BLACKFORT_TESTNET]: "BXN Testnet",
  [ChainID.APECHAIN_MAINNET]: "Ape Mainnet",
  [ChainID.APECHAIN_CURTIS_TESTNET]: "Ape Curtis",
  [ChainID.EDUCHAIN]: "Edu Chain",
  [ChainID.SHAPE_MAINNET]: "Shape Mainnet",
  [ChainID.SHAPE_SEPOLIA]: "Shape Sepolia",
  [ChainID.WORLD_MAINNET]: "World Chain",
  [ChainID.WORLD_SEPOLIA]: "World Chain Sepolia",
  [ChainID.CHILIZ]: "Chiliz Chain",
  [ChainID.CHILIZ_SPICY_TESTNET]: "Chiliz Spicy Testnet",
  [ChainID.SONIC]: "Sonic Mainnet",
  [ChainID.SONIC_TESTNET]: "Sonic Blase Testnet",
  [ChainID.INK]: "Ink Mainnet",
  [ChainID.INK_SEPOLIA]: "Ink Sepolia",
  [ChainID.ABSTRACT_TESTNET]: "Abstract Testnet",
  [ChainID.STACK]: "Stack",
  [ChainID.STACK_TESTNET]: "Stack Testnet",
  [ChainID.HEMI_TESTNET]: "Hemi Sepolia",
  [ChainID.MINT]: "Mint Mainnet",
  [ChainID.MINT_SEPOLIA]: "Mint Sepolia",
  [ChainID.TABI_TESTNET]: "Tabi Testnet",
  [ChainID.SUPERPOSITION]: "Superposition",
  [ChainID.SUPERPOSITION_TESTNET]: "Superposition Testnet",
  [ChainID.SWELLCHAIN]: "Swell Chain",
  [ChainID.SWELLCHAIN_TESTNET]: "Swell Testnet",
  [ChainID.PLUME]: "Plume",
  [ChainID.PLUME_TESTNET]: "Plume Testnet",
  [ChainID.DARWINIA]: "Darwinia",
  [ChainID.DARWINIA_CRAB]: "Darwinia Crab",
  [ChainID.ANCIENT_8]: "Ancient8",
  [ChainID.ANCIENT_8_TESTNET]: "Ancient8 Celestia Testnet",
  [ChainID.AUTHEO_TESTNET]: "Autheo Testnet",
  [ChainID.EPHEMERY_TESTNET]: "ephemery-testnet",
  [ChainID.MONAD_TESTNET]: "Monad Testnet",
  [ChainID.BOUNCEBIT]: "BounceBit",
  [ChainID.BOUNCEBIT_TESTNET]: "BounceBit Testnet",
  [ChainID.PHAROS_DEVNET]: "Pharos Devnet",
}
